name: Setup
description: Setup the project

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
        registry-url: "https://registry.npmjs.org"
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: "pnpm"
    - name: Install dependencies
      shell: bash
      run: pnpm ci
