name: Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  statuses: read
  contents: read

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Setup project
        uses: ./.github/actions/setup
      - name: Run prettier
        run: pnpm prettier --check "**/*.{ts,tsx,md}"
