name: Publish

on:
  workflow_call:
    inputs:
      pre-release:
        type: boolean
        default: false
        description: Publish as pre-release
  workflow_dispatch:
    inputs:
      pre-release:
        type: boolean
        default: false
        description: Publish as pre-release

permissions:
  contents: read
  packages: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup project
        uses: ./.github/actions/setup
      - name: Create npm configuration
        shell: bash
        run: |
          echo "registry=https://registry.npmjs.org/" > .npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
          echo "always-auth=true" >> .npmrc
      - name: Publish package
        if: ${{ !inputs.pre-release }}
        run: pnpm publish --no-git-checks --access public
      - name: Publish package (pre-release)
        if: ${{ inputs.pre-release }}
        run: pnpm publish --no-git-checks --access public --tag next
